version: "3.9"

services:
  backend:
    build:
      context: ./backend

    container_name: imoh-ai-backend

    env_file:
      - ./backend/.env

    ports:
      - "5001:5001"

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://51.20.129.94:5001

    container_name: imoh-ai-frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

    restart: unless-stopped
