name: Deploy Imoh AI

on:
  push:
    branches:
      - main
    paths:
      - "imoh-ai/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/ubuntu/test_repo/imoh-ai
            echo "Current directory:"
            pwd
            ls -la

            echo "Cleaning Docker..."
            docker system prune -af || true
            docker builder prune -af || true

            echo "Building Docker images..."
            docker compose build --pull
            
            echo "Starting containers..."
            docker compose up -d --remove-orphans

            echo "Starting containers..."
            docker compose up -d --remove-orphans
            echo "Deployment completed successfully!"
